spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  tracing:
    enabled: false

resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      geolocation:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2
        minimum-number-of-calls: 3
        register-health-indicator: true
  retry:
    retryAspectOrder: 2
    instances:
      geolocation:
        max-attempts: 3
        wait-duration: 100ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 1.5
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
          - java.net.SocketTimeoutException
          - java.net.ConnectException
        ignore-exceptions:
          - com.task.application.exception.GeoLocationException
